from tkinter import *
def window():
    def get_input():
        s = user_input_value.get()
        # Label(text="User :"+s+"\t"+"Bot :"+s).pack()
        Label(text="User :"+s).pack(anchor=W)
        Label(text="Bot: "+s).pack(anchor=W)
        user_input.set("")
    root = Tk()
    root.geometry("400x600")
    root.title("-- CHATBOT --")
    Frame(root,bg="grey").pack(side=TOP)
    Label(text="Aman Kumar Sahu -- BT21CSE005 \nRohith Raj -- BT21CSE006 \nIshu Raj -- BT21CSE007 \nAditya Deokar -- BT21CSE008").pack()
    Label(text="--- AIRLINE CHATBOT - --").pack()
    frb =  Frame(root,bg="red")
    frb.pack(side=BOTTOM)
    user_input = StringVar()
    frin = Frame(root,bg="yellow")
    user_input_value = Entry(root, textvariable=user_input,width=50)
    b = Button(frb,fg="blue",text="SEND",command=get_input)
    user_input_value.pack(side=BOTTOM)
    b.pack()
    Scroll = Scrollbar().place(height=600)
    root.mainloop()
    return user_input_value.get() 